# Generated by Django 3.1 on 2022-06-12 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('color', models.PositiveSmallIntegerField(choices=[(1, 'primary'), (2, 'danger'), (3, 'success')])),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.source', verbose_name='source')),
            ],
        ),
    ]
