# Generated by Django 3.1 on 2022-06-12 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0002_auto_20220612_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='source.source', verbose_name='source'),
        ),
    ]
