# Generated by Django 3.1 on 2023-01-06 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('pakage_type', models.CharField(choices=[('GOLD', 'Gold'), ('SILVER', 'Silver'), ('DIAMOND', 'Diamond')], max_length=10)),
                ('six_months_price', models.DecimalField(decimal_places=2, default=10, max_digits=6)),
                ('one_year_price', models.DecimalField(decimal_places=2, default=10, max_digits=6)),
                ('two_year_price', models.DecimalField(decimal_places=2, default=10, max_digits=6)),
                ('description', models.TextField(verbose_name='Description')),
                ('features', models.ManyToManyField(to='payments.PackageFeature')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=100)),
                ('amount', models.IntegerField(default=0)),
                ('order_len', models.CharField(choices=[('SIX_MONTHS', '6 Months'), ('ONE_YEAR', '1 year'), ('TWO_YEAR', '2 Years')], max_length=20)),
                ('success', models.BooleanField(default=False)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(auto_now=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
