# Generated by Django 3.1 on 2023-01-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='currency',
            field=models.CharField(choices=[('EGP', 'EGP')], default='EGP', max_length=50),
        ),
    ]
