# Generated by Django 3.1 on 2023-01-06 21:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0004_auto_20230106_2102'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Subscription',
        ),
    ]
