# Generated by Django 3.1 on 2023-01-06 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20230106_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='order_code',
            new_name='order_id',
        ),
    ]
