# Generated by Django 3.1 on 2023-01-07 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0007_auto_20230106_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_type',
            field=models.CharField(choices=[('G', 'Gold'), ('S', 'Silver'), ('D', 'Diamond')], max_length=10),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscribe_duration',
            field=models.CharField(choices=[('1', '6 Months'), ('2', '1 year'), ('3', '2 Years')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
