# Generated by Django 3.1 on 2023-01-07 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_auto_20230107_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='subscribe_duration',
            new_name='duration',
        ),
    ]
